networks:
  rest-service:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgresql
    restart: always
    networks:
      - rest-service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
